
export const ADMIN_TYIPE={

SET_CURRENT_USER_START:'admin/SET_CURRENT_USER_START',
SET_CURRENT_USER_SUCCES:'admin/SET_CURRENT_USER_SUCCES',
SET_CURRENT_USER_FAILD:'admin/SET_CURRENT_USER_FAILD',
SIGN_OUT_USER:'admin/SIGN_OUT_USER'
}
