export const PRODUCTS_TYPES={
    FETCH_PRODUCTS_DATA_START:'products/FETCH_PRODUCTS_DATA_START',
    FETCH_PRODUCTS_DATA_FAILD:'products/FETCH_PRODUCTS_DATA_FAILD',
    FETCH_PRODUCTS_DATA_SUCCES:'products/FETCH_PRODUCTS_DATA_SUCCES',


    SET_PRODUCTS_LAST_PRODUCT_ID_START:"products/SET_PRODUCTS_LAST_PRODUCT_ID_START",
    SET_PRODUCTS_LAST_PRODUCT_ID_FAILD:"products/SET_PRODUCTS_LAST_PRODUCT_ID_FAILD",
    SET_PRODUCTS_LAST_PRODUCT_ID_SUCCES:"products/SET_PRODUCTS_LAST_PRODUCT_ID_SUCCES",
   
    SET_CHANGE_PRODUCT_DETAILS_START:'products/SET_CHANGE_PRODUCT_DETAILS_START',
    SET_CHANGE_PRODUCT_DETAILS_FAILD:'products/SET_CHANGE_PRODUCT_DETAILS_FAILD',
    SET_CHANGE_PRODUCT_DETAILS_SUCCES:'products/SET_CHANGE_PRODUCT_DETAILS_SUCCES',

    SET_REMOVE_PRODUCT_START:'products/SET_REMOVE_PRODUCT_START',
    SET_REMOVE_PRODUCT_FAILD:'products/SET_REMOVE_PRODUCT_FAILD',
    SET_REMOVE_PRODUCT_SUCCES:'products/SET_REMOVE_PRODUCT_SUCCES',

    SET_ADD_PRODUCT_START:'products/SET_ADD_PRODUCT_START',
    SET_ADD_PRODUCT_FAILD:'products/ SET_ADD_PRODUCT_FAILD:',
    SET_ADD_PRODUCT_SUCCES:'products/SET_ADD_PRODUCT_SUCCES:',


}