export const PRODUCTS_TYPES={
    FETCH_PRODUCTS_DATA_START:'products/FETCH_PRODUCTS_DATA_START',
    FETCH_PRODUCTS_DATA_FAILD:'products/FETCH_PRODUCTS_DATA_FAILD',
    FETCH_PRODUCTS_DATA_SUCCES:'products/FETCH_PRODUCTS_DATA_SUCCES',
   
  

}