
export const ORDERS_TYPES={
    FETCH_ORDERS_START:'orders/FETCH_ORDERS_START',
    FETCH_ORDERS_SUCCESS:'orders/FETCH_ORDERS_SUCCESS',
    FETCH_ORDERS_FAILD:'orders/FETCH_ORDERS_FAILD',
    REMOVE_ORDER_DATA_START:'orders/ REMOVE_ORDER_DATA_START',
    REMOVE_ORDER_DATA_FAILD:'orders/ REMOVE_ORDER_DATA_FAILD',
    REMOVE_ORDER_DATA_SUCCESS:'orders/ REMOVE_ORDER_DATA_SUCCESS',
    IS_BTN_CLICKED:'orders/IS_BTN_CLICKED',
    FETCH_ORDERS_DETAILS_FAILD:'orders/FETCH_ORDERS_FAILD',
    FETCH_ORDERS_DETAILS_START:'orders/FETCH_ORDERS_DETAILS_START',
    FETCH_ORDERS_DETAILS_SUCCESS:'orders/FETCH_ORDERS_DETAILS_SUCCESS'
  
}